
import { Vocabulary } from './types';

export const LESSON_TITLES: Record<number, string> = {
  1: "Chào hỏi - Giới thiệu",
  2: "Vật dụng xung quanh",
  3: "Địa điểm - Nơi chốn",
  4: "Thời gian - Ngày giờ",
  5: "Di chuyển - Đi lại",
  6: "Hành động - Ăn uống",
  7: "Công cụ - Cách thức",
  8: "Tính từ - Miêu tả",
  9: "Sở thích - Khả năng",
  10: "Sự hiện diện - Có gì",
  11: "Số lượng - Cách đếm",
  12: "Quá khứ - So sánh",
  13: "Mong muốn - Dự định",
  14: "Yêu cầu - Thể Te",
  15: "Cho phép - Cấm đoán",
  16: "Trình tự hành động",
  17: "Nghĩa vụ - Thể Nai",
  18: "Khả năng - Thể Từ điển",
  19: "Kinh nghiệm - Thể Ta",
  20: "Thể thông thường",
  21: "Ý kiến - Phán đoán",
  22: "Mệnh đề bổ ngữ",
  23: "Thời điểm - Khi nào",
  24: "Cho nhận - Biếu tặng",
  25: "Điều kiện - Giả định"
};

export const INITIAL_VOCAB: Vocabulary[] = [
  // --- BÀI 1 ---
  { id: 'l1-1', kanji: "私", reading: "わたし", meaning: "tôi", category: 'kanji', lesson: 1 },
  { id: 'l1-2', kanji: "あなた", reading: "あなた", meaning: "anh/chị, ông/bà, bạn (ngôi thứ II số ít)", category: 'general', lesson: 1 },
  { id: 'l1-3', kanji: "あの人", reading: "あのひと", meaning: "người kia, người đó", category: 'kanji', lesson: 1 },
  { id: 'l1-4', kanji: "あの方", reading: "あのかた", meaning: "vị kia (cách nói lịch sự của \"ano hito\")", category: 'kanji', lesson: 1 },
  { id: 'l1-5', kanji: "～さん", reading: "～さん", meaning: "anh, chị, ông, bà (hậu tố thêm sau tên)", category: 'general', lesson: 1 },
  { id: 'l1-6', kanji: "～ちゃん", reading: "～ちゃん", meaning: "hậu tố thêm sau tên trẻ em", category: 'general', lesson: 1 },
  { id: 'l1-7', kanji: "～人", reading: "～じん", meaning: "người (nước ~)", category: 'kanji', lesson: 1 },
  { id: 'l1-8', kanji: "先生", reading: "せんせい", meaning: "thầy/cô (không dùng khi giới thiệu nghề nghiệp của mình)", category: 'kanji', lesson: 1 },
  { id: 'l1-9', kanji: "教師", reading: "きょうし", meaning: "giáo viên", category: 'kanji', lesson: 1 },
  { id: 'l1-10', kanji: "学生", reading: "がくせい", meaning: "học sinh, sinh viên", category: 'kanji', lesson: 1 },
  { id: 'l1-11', kanji: "会社員", reading: "かいしゃいん", meaning: "nhân viên công ty", category: 'kanji', lesson: 1 },
  { id: 'l1-12', kanji: "社員", reading: "しゃいん", meaning: "nhân viên công ty (dùng kèm theo tên công ty)", category: 'kanji', lesson: 1 },
  { id: 'l1-13', kanji: "銀行員", reading: "ぎんこういん", meaning: " nhân viên ngân hàng", category: 'kanji', lesson: 1 },
  { id: 'l1-14', kanji: "医者", reading: "いしゃ", meaning: "bác sĩ", category: 'kanji', lesson: 1 },
  { id: 'l1-15', kanji: "研究者", reading: "けんきゅうしゃ", meaning: "nhà nghiên cứu", category: 'kanji', lesson: 1 },
  { id: 'l1-16', kanji: "大学", reading: "だいがく", meaning: "đại học, trường đại học", category: 'kanji', lesson: 1 },
  { id: 'l1-17', kanji: "病院", reading: "びょういん", meaning: "bệnh viện", category: 'kanji', lesson: 1 },
  { id: 'l1-18', kanji: "誰", reading: "だれ", meaning: "ai", category: 'kanji', lesson: 1 },
  { id: 'l1-19', kanji: "どなた", reading: "どなた", meaning: "vị nào (cách nói lịch sự của \"dare\")", category: 'general', lesson: 1 },
  { id: 'l1-20', kanji: "～歳", reading: "～さい", meaning: "～ tuổi", category: 'kanji', lesson: 1 },
  { id: 'l1-21', kanji: "何歳", reading: "なんさい", meaning: "mấy tuổi, bao nhiêu tuổi", category: 'kanji', lesson: 1 },
  { id: 'l1-22', kanji: "おいくつ", reading: "おいくつ", meaning: "bao nhiêu tuổi (cách nói lịch sự của \"nansai\")", category: 'general', lesson: 1 },
  { id: 'l1-23', kanji: "はい", reading: "はい", meaning: "vâng, dạ", category: 'general', lesson: 1 },
  { id: 'l1-24', kanji: "いいえ", reading: "いいえ", meaning: "không", category: 'general', lesson: 1 },
  { id: 'l1-c1', kanji: "初めまして", reading: "はじめまして", meaning: "Rất hân hạnh được gặp anh/chị. (Lời chào lần đầu gặp mặt)", category: 'general', lesson: 1 },
  { id: 'l1-c2', kanji: "～から 来ました", reading: "～から きました", meaning: "Tôi đến từ ～.", category: 'kanji', lesson: 1 },
  { id: 'l1-c3', kanji: "[どうぞ] よろしく [お願いします]", reading: "よろしく おねがいします", meaning: "Rất vui được làm quen với anh/chị. (Rất mong nhận được sự giúp đỡ)", category: 'kanji', lesson: 1 },
  { id: 'l1-c4', kanji: "失礼ですが", reading: "しつれいですが", meaning: "Xin lỗi... (dùng khi hỏi thông tin cá nhân)", category: 'kanji', lesson: 1 },
  { id: 'l1-c5', kanji: "お名前", reading: "おなまえは？", meaning: "Tên anh/chị là gì?", category: 'kanji', lesson: 1 },
  { id: 'l1-c6', kanji: "こちらは ～さんです", reading: "こちらは ～さんです", meaning: "Đây là anh/chị/ông/bà ～.", category: 'general', lesson: 1 },

  // --- BÀI 2 ---
  { id: 'l2-1', kanji: "これ", reading: "これ", meaning: "cái này, đây (vật ở gần người nói)", category: 'general', lesson: 2 },
  { id: 'l2-2', kanji: "それ", reading: "それ", meaning: "cái đó, đó (vật ở gần người nghe)", category: 'general', lesson: 2 },
  { id: 'l2-3', kanji: "あれ", reading: "あれ", meaning: "cái kia, kia (vật ở xa cả hai)", category: 'general', lesson: 2 },
  { id: 'l2-4', kanji: "この～", reading: "この～", meaning: "~ này (gần người nói)", category: 'general', lesson: 2 },
  { id: 'l2-5', kanji: "その～", reading: "その～", meaning: "~ đó (gần người nghe)", category: 'general', lesson: 2 },
  { id: 'l2-6', kanji: "あの～", reading: "あの～", meaning: "~ kia (xa cả hai)", category: 'general', lesson: 2 },
  { id: 'l2-7', kanji: "本", reading: "ほん", meaning: "sách", category: 'kanji', lesson: 2 },
  { id: 'l2-8', kanji: "辞書", reading: "じしょ", meaning: "từ điển", category: 'kanji', lesson: 2 },
  { id: 'l2-9', kanji: "雑誌", reading: "ざっし", meaning: "tạp chí", category: 'kanji', lesson: 2 },
  { id: 'l2-10', kanji: "新聞", reading: "しんぶん", meaning: "báo", category: 'kanji', lesson: 2 },
  { id: 'l2-11', kanji: "ノート", reading: "ノート", meaning: "vở", category: 'general', lesson: 2 },
  { id: 'l2-12', kanji: "手帳", reading: "てちょう", meaning: "sổ tay", category: 'kanji', lesson: 2 },
  { id: 'l2-13', kanji: "名刺", reading: "めいし", meaning: "danh thiếp", category: 'kanji', lesson: 2 },
  { id: 'l2-14', kanji: "カード", reading: "カード", meaning: "thẻ, các, cạc", category: 'general', lesson: 2 },
  { id: 'l2-15', kanji: "鉛筆", reading: "えんぴつ", meaning: "bút chì", category: 'kanji', lesson: 2 },
  { id: 'l2-16', kanji: "ボールペン", reading: "ボールペン", meaning: "bút bi", category: 'general', lesson: 2 },
  { id: 'l2-17', kanji: "シャープペンシル", reading: "シャープペンシル", meaning: "bút chì kim, bút chì bấm", category: 'general', lesson: 2 },
  { id: 'l2-18', kanji: "かぎ", reading: "かぎ", meaning: "chìa khóa", category: 'general', lesson: 2 },
  { id: 'l2-19', kanji: "時計", reading: "とけい", meaning: "đồng hồ", category: 'kanji', lesson: 2 },
  { id: 'l2-20', kanji: "傘", reading: "かさ", meaning: "ô, dù", category: 'kanji', lesson: 2 },
  { id: 'l2-21', kanji: "かばん", reading: "かばん", meaning: "cặp sách, túi sách", category: 'general', lesson: 2 },
  { id: 'l2-22', kanji: "CD", reading: "CD", meaning: "đĩa CD", category: 'general', lesson: 2 },
  { id: 'l2-23', kanji: "テレビ", reading: "テレビ", meaning: "tivi", category: 'general', lesson: 2 },
  { id: 'l2-24', kanji: "ラジオ", reading: "ラジオ", meaning: "radio", category: 'general', lesson: 2 },
  { id: 'l2-25', kanji: "カメラ", reading: "カメラ", meaning: "máy ảnh", category: 'general', lesson: 2 },
  { id: 'l2-26', kanji: "コンピューター", reading: "コンピューター", meaning: "máy vi tính", category: 'general', lesson: 2 },
  { id: 'l2-27', kanji: "車", reading: "くるま", meaning: "ô tô, xe hơi", category: 'kanji', lesson: 2 },
  { id: 'l2-28', kanji: "机", reading: "つくえ", meaning: "bàn", category: 'kanji', lesson: 2 },
  { id: 'l2-29', kanji: "いす", reading: "いす", meaning: "ghế", category: 'general', lesson: 2 },
  { id: 'l2-30', kanji: "チョコレート", reading: "チョコレート", meaning: "sôcôla", category: 'general', lesson: 2 },
  { id: 'l2-31', kanji: "コーヒー", reading: "コーヒー", meaning: "cà phê", category: 'general', lesson: 2 },
  { id: 'l2-32', kanji: "[お]土産", reading: "[お]みやげ", meaning: "quà (mua khi đi xa về hoặc mang đi thăm)", category: 'kanji', lesson: 2 },
  { id: 'l2-33', kanji: "英語", reading: "えいご", meaning: "tiếng Anh", category: 'kanji', lesson: 2 },
  { id: 'l2-34', kanji: "日本語", reading: "にほんご", meaning: "tiếng Nhật", category: 'kanji', lesson: 2 },
  { id: 'l2-35', kanji: "～語", reading: "～ご", meaning: "tiếng ~", category: 'kanji', lesson: 2 },
  { id: 'l2-36', kanji: "何", reading: "なん", meaning: "cái gì, gì", category: 'kanji', lesson: 2 },
  { id: 'l2-37', kanji: "そう", reading: "そう", meaning: "đúng vậy, vậy", category: 'general', lesson: 2 },
  { id: 'l2-c1', kanji: "あのう", reading: "あのう", meaning: "à, ... (dùng khi ngập ngừng, do dự)", category: 'general', lesson: 2 },
  { id: 'l2-c2', kanji: "えっ", reading: "えっ", meaning: "Hả? (dùng khi ngạc nhiên)", category: 'general', lesson: 2 },
  { id: 'l2-c3', kanji: "どうぞ", reading: "どうぞ", meaning: "Xin mời.", category: 'general', lesson: 2 },
  { id: 'l2-c4', kanji: "[どうも] ありがとう [ございます]", reading: "ありがとう ございます", meaning: "Xin [chân thành] cám ơn.", category: 'general', lesson: 2 },
  { id: 'l2-c5', kanji: "そうですか", reading: "そうですか", meaning: "Thế à.", category: 'general', lesson: 2 },
  { id: 'l2-c6', kanji: "違います", reading: "ちがいます", meaning: "Không phải, không đúng, sai rồi.", category: 'verb', lesson: 2 },
  { id: 'l2-c7', kanji: "あ", reading: "あ", meaning: "A! / Ôi!", category: 'general', lesson: 2 },
  { id: 'l2-c8', kanji: "これから お世話になります", reading: "これから おせわになります", meaning: "Từ nay tôi rất mong được sự giúp đỡ của anh/chị.", category: 'kanji', lesson: 2 },
  { id: 'l2-c9', kanji: "こちらこそ [どうぞ] よろしく [お願いします]", reading: "こちらこそ よろしく おねがいします", meaning: "Chính tôi mới là người mong được sự giúp đỡ của anh/chị.", category: 'kanji', lesson: 2 },

  // --- BÀI 3 ---
  { id: 'l3-1', kanji: "教室", reading: "きょうしつ", meaning: "lớp học, phòng học", category: 'kanji', lesson: 3 },
  { id: 'l3-2', kanji: "食堂", reading: "しょくどう", meaning: "nhà ăn", category: 'kanji', lesson: 3 },
  { id: 'l3-3', kanji: "事務所", reading: "じむしょ", meaning: "văn phòng", category: 'kanji', lesson: 3 },
  { id: 'l3-4', kanji: "会議室", reading: "かいぎしつ", meaning: "phòng họp", category: 'kanji', lesson: 3 },
  { id: 'l3-5', kanji: "受付", reading: "うけつけ", meaning: "quầy lễ tân, phòng thường trực", category: 'kanji', lesson: 3 },
  { id: 'l3-6', kanji: "ロビー", reading: "ロビー", meaning: "hành lang, đại sảnh", category: 'general', lesson: 3 },
  { id: 'l3-7', kanji: "部屋", reading: "へや", meaning: "căn phòng", category: 'kanji', lesson: 3 },
  { id: 'l3-8', kanji: "トイレ (お手洗い)", reading: "トイレ (おてあらい)", meaning: "toa-lét, nhà vệ sinh", category: 'kanji', lesson: 3 },
  { id: 'l3-9', kanji: "階段", reading: "かいだん", meaning: "cầu thang", category: 'kanji', lesson: 3 },
  { id: 'l3-10', kanji: "エレベーター", reading: "エレベーター", meaning: "thang máy", category: 'general', lesson: 3 },
  { id: 'l3-11', kanji: "エスカレーター", reading: "エスカレーター", meaning: "thang cuốn", category: 'general', lesson: 3 },
  { id: 'l3-12', kanji: "[お]国", reading: "[お]くに", meaning: "nước (của anh/chị)", category: 'kanji', lesson: 3 },
  { id: 'l3-13', kanji: "会社", reading: "かいしゃ", meaning: "công ty", category: 'kanji', lesson: 3 },
  { id: 'l3-14', kanji: "うち", reading: "うち", meaning: "nhà", category: 'general', lesson: 3 },
  { id: 'l3-15', kanji: "電話", reading: "でんわ", meaning: "điện thoại", category: 'kanji', lesson: 3 },
  { id: 'l3-16', kanji: "靴", reading: "くつ", meaning: "giày", category: 'kanji', lesson: 3 },
  { id: 'l3-17', kanji: "ネクタイ", reading: "ネクタイ", meaning: "cà vạt", category: 'general', lesson: 3 },
  { id: 'l3-18', kanji: "ワイン", reading: "ワイン", meaning: "rượu vang", category: 'general', lesson: 3 },
  { id: 'l3-19', kanji: "タバコ", reading: "タバコ", meaning: "thuốc lá", category: 'general', lesson: 3 },
  { id: 'l3-20', kanji: "売り場", reading: "うりば", meaning: "quầy bán (trong bách hóa)", category: 'kanji', lesson: 3 },
  { id: 'l3-21', kanji: "地下", reading: "ちか", meaning: "tầng hầm, dưới mặt đất", category: 'kanji', lesson: 3 },
  { id: 'l3-22', kanji: "～階", reading: "～かい (～がい)", meaning: "tầng thứ ~", category: 'kanji', lesson: 3 },
  { id: 'l3-23', kanji: "何階", reading: "なんがい", meaning: "tầng mấy", category: 'kanji', lesson: 3 },
  { id: 'l3-24', kanji: "～円", reading: "～えん", meaning: "yên", category: 'kanji', lesson: 3 },
  { id: 'l3-25', kanji: "いくら", reading: "いくら", meaning: "bao nhiêu tiền", category: 'general', lesson: 3 },
  { id: 'l3-26', kanji: "百", reading: "ひゃく", meaning: "trăm", category: 'kanji', lesson: 3 },
  { id: 'l3-27', kanji: "千", reading: "せん", meaning: "nghìn", category: 'kanji', lesson: 3 },
  { id: 'l3-28', kanji: "万", reading: "まん", meaning: "mười nghìn, vạn", category: 'kanji', lesson: 3 },
  { id: 'l3-29', kanji: "自動販売機", reading: "じどうはんばいき", meaning: "máy bán hàng tự động", category: 'kanji', lesson: 3 },
  { id: 'l3-c1', kanji: "すみません", reading: "すみません", meaning: "Xin lỗi.", category: 'general', lesson: 3 },
  { id: 'l3-c2', kanji: "どうも", reading: "どうも", meaning: "Cám ơn.", category: 'general', lesson: 3 },
  { id: 'l3-c3', kanji: "いらっしゃいませ", reading: "いらっしゃいませ", meaning: "Xin chào quý khách, mời quý khách vào.", category: 'general', lesson: 3 },
  { id: 'l3-c4', kanji: "[～を] 見せてください", reading: "[～を] みせてください", meaning: "Cho tôi xem [～].", category: 'kanji', lesson: 3 },
  { id: 'l3-c5', kanji: "じゃ", reading: "じゃ", meaning: "Thế thì, vậy thì.", category: 'general', lesson: 3 },
  { id: 'l3-c6', kanji: "[～を] ください", reading: "[～を] ください", meaning: "Cho tôi [～].", category: 'general', lesson: 3 },

  // --- BÀI 4 ---
  { id: 'l4-1', kanji: "起きます", reading: "おきます", meaning: "dậy, thức dậy", category: 'verb', lesson: 4 },
  { id: 'l4-2', kanji: "寝ます", reading: "ねます", meaning: "ngủ, đi ngủ", category: 'verb', lesson: 4 },
  { id: 'l4-3', kanji: "働きます", reading: "はたらきます", meaning: "làm việc", category: 'verb', lesson: 4 },
  { id: 'l4-4', kanji: "休みます", reading: "やすみます", meaning: "nghỉ, nghỉ ngơi", category: 'verb', lesson: 4 },
  { id: 'l4-5', kanji: "勉強します", reading: "べんきょうします", meaning: "học", category: 'verb', lesson: 4 },
  { id: 'l4-6', kanji: "終わります", reading: "おわります", meaning: "hết, kết thúc, xong", category: 'verb', lesson: 4 },
  { id: 'l4-7', kanji: "デパート", reading: "デパート", meaning: "bách hóa", category: 'general', lesson: 4 },
  { id: 'l4-8', kanji: "銀行", reading: "ぎんこう", meaning: "ngân hàng", category: 'kanji', lesson: 4 },
  { id: 'l4-9', kanji: "郵便局", reading: "ゆうびんきょく", meaning: "bưu điện", category: 'kanji', lesson: 4 },
  { id: 'l4-10', kanji: "図書館", reading: "としょかん", meaning: "thư viện", category: 'kanji', lesson: 4 },
  { id: 'l4-11', kanji: "美術館", reading: "びじゅつかん", meaning: "bảo tàng mỹ thuật", category: 'kanji', lesson: 4 },
  { id: 'l4-12', kanji: "今", reading: "いま", meaning: "bây giờ", category: 'kanji', lesson: 4 },
  { id: 'l4-13', kanji: "～時", reading: "～じ", meaning: "～ giờ", category: 'kanji', lesson: 4 },
  { id: 'l4-14', kanji: "～分", reading: "～ふん（～ぷん）", meaning: "～ phút", category: 'kanji', lesson: 4 },
  { id: 'l4-15', kanji: "半", reading: "はん", meaning: "rưỡi, nửa", category: 'kanji', lesson: 4 },
  { id: 'l4-16', kanji: "何時", reading: "なんじ", meaning: "mấy giờ", category: 'kanji', lesson: 4 },
  { id: 'l4-17', kanji: "何分", reading: "なんぷん", meaning: "mấy phút", category: 'kanji', lesson: 4 },
  { id: 'l4-18', kanji: "午前", reading: "ごぜん", meaning: "sáng, trước 12 giờ trưa (AM)", category: 'kanji', lesson: 4 },
  { id: 'l4-19', kanji: "午後", reading: "ごご", meaning: "chiều, sau 12 giờ trưa (PM)", category: 'kanji', lesson: 4 },
  { id: 'l4-20', kanji: "朝", reading: "あさ", meaning: "buổi sáng, sáng", category: 'kanji', lesson: 4 },
  { id: 'l4-21', kanji: "昼", reading: "ひる", meaning: "buổi trưa, trưa", category: 'kanji', lesson: 4 },
  { id: 'l4-22', kanji: "晩（夜）", reading: "ばん（よる）", meaning: "buổi tối, tối", category: 'kanji', lesson: 4 },
  { id: 'l4-23', kanji: "昼休み", reading: "ひるやすみ", meaning: "nghỉ trưa", category: 'kanji', lesson: 4 },
  { id: 'l4-24', kanji: "おととい", reading: "おととい", meaning: "hôm kia", category: 'general', lesson: 4 },
  { id: 'l4-25', kanji: "きのう", reading: "きのう", meaning: "hôm qua", category: 'general', lesson: 4 },
  { id: 'l4-26', kanji: "きょう", reading: "きょう", meaning: "hôm nay", category: 'general', lesson: 4 },
  { id: 'l4-27', kanji: "あした", reading: "あした", meaning: "ngày mai", category: 'general', lesson: 4 },
  { id: 'l4-28', kanji: "あさって", reading: "あさって", meaning: "ngày kia", category: 'general', lesson: 4 },
  { id: 'l4-29', kanji: "けさ", reading: "けさ", meaning: "sáng nay", category: 'general', lesson: 4 },
  { id: 'l4-30', kanji: "今晩", reading: "こんばん", meaning: "tối nay", category: 'kanji', lesson: 4 },
  { id: 'l4-31', kanji: "休み", reading: "やすみ", meaning: "nghỉ, nghỉ phép, ngày nghỉ", category: 'kanji', lesson: 4 },
  { id: 'l4-32', kanji: "毎朝", reading: "まいあさ", meaning: "hàng sáng, mỗi sáng", category: 'kanji', lesson: 4 },
  { id: 'l4-33', kanji: "毎晩", reading: "まいばん", meaning: "hàng tối, mỗi tối", category: 'kanji', lesson: 4 },
  { id: 'l4-34', kanji: "毎日", reading: "まいにち", meaning: "hàng ngày, mỗi ngày", category: 'kanji', lesson: 4 },
  { id: 'l4-35', kanji: "月曜日", reading: "げつようび", meaning: "thứ hai", category: 'kanji', lesson: 4 },
  { id: 'l4-36', kanji: "火曜日", reading: "かようび", meaning: "thứ ba", category: 'kanji', lesson: 4 },
  { id: 'l4-37', kanji: "水曜日", reading: "すいようび", meaning: "thứ tư", category: 'kanji', lesson: 4 },
  { id: 'l4-38', kanji: "木曜日", reading: "もくようび", meaning: "thứ năm", category: 'kanji', lesson: 4 },
  { id: 'l4-39', kanji: "金曜日", reading: "きんようび", meaning: "thứ sáu", category: 'kanji', lesson: 4 },
  { id: 'l4-40', kanji: "土曜日", reading: "どようび", meaning: "thứ bảy", category: 'kanji', lesson: 4 },
  { id: 'l4-41', kanji: "日曜日", reading: "にちようび", meaning: "chủ nhật", category: 'kanji', lesson: 4 },
  { id: 'l4-42', kanji: "何曜日", reading: "なんようび", meaning: "thứ mấy", category: 'kanji', lesson: 4 },
  { id: 'l4-43', kanji: "番号", reading: "ばんごう", meaning: "số", category: 'kanji', lesson: 4 },
  { id: 'l4-44', kanji: "何番", reading: "なんばん", meaning: "số bao nhiêu, số mấy", category: 'kanji', lesson: 4 },
  { id: 'l4-45', kanji: "試験", reading: "しけん", meaning: "thi, kỳ thi, kiểm tra", category: 'kanji', lesson: 4 },
  { id: 'l4-46', kanji: "会議", reading: "かいぎ", meaning: "cuộc họp, hội nghị", category: 'kanji', lesson: 4 },
  { id: 'l4-47', kanji: "映画", reading: "えいが", meaning: "phim, điện ảnh", category: 'kanji', lesson: 4 },
  { id: 'l4-48', kanji: "～ từ", reading: "～から", meaning: "từ", category: 'general', lesson: 4 },
  { id: 'l4-49', kanji: "～ đến", reading: "～まで", meaning: "đến", category: 'general', lesson: 4 },
  { id: 'l4-50', kanji: "～ và ～", reading: "～と～", meaning: "và (dùng để nối danh từ)", category: 'general', lesson: 4 },

  // --- BÀI 5 ---
  { id: 'l5-1', kanji: "行きます", reading: "いきます", meaning: "đi", category: 'verb', lesson: 5 },
  { id: 'l5-2', kanji: "来ます", reading: "きます", meaning: "đến", category: 'verb', lesson: 5 },
  { id: 'l5-3', kanji: "帰ります", reading: "かえります", meaning: "về", category: 'verb', lesson: 5 },
  { id: 'l5-4', kanji: "学校", reading: "がっこう", meaning: "trường học", category: 'kanji', lesson: 5 },
  { id: 'l5-5', kanji: "スーパー", reading: "スーパー", meaning: "siêu thị", category: 'general', lesson: 5 },
  { id: 'l5-6', kanji: "駅", reading: "えき", meaning: "ga, nhà ga", category: 'kanji', lesson: 5 },
  { id: 'l5-7', kanji: "飛行機", reading: "ひこうき", meaning: "máy bay", category: 'kanji', lesson: 5 },
  { id: 'l5-8', kanji: "船", reading: "ふね", meaning: "thuyền, tàu thủy", category: 'kanji', lesson: 5 },
  { id: 'l5-9', kanji: "電車", reading: "でんしゃ", meaning: "tàu điện", category: 'kanji', lesson: 5 },
  { id: 'l5-10', kanji: "地下鉄", reading: "ちかてつ", meaning: "tàu điện ngầm", category: 'kanji', lesson: 5 },
  { id: 'l5-11', kanji: "新幹線", reading: "しんかんせん", meaning: "tàu Shinkansen (tàu điện cao tốc)", category: 'kanji', lesson: 5 },
  { id: 'l5-12', kanji: "バス", reading: "バス", meaning: "xe buýt", category: 'general', lesson: 5 },
  { id: 'l5-13', kanji: "タクシー", reading: "タクシー", meaning: "tắc-xi", category: 'general', lesson: 5 },
  { id: 'l5-14', kanji: "自転車", reading: "じてんしゃ", meaning: "xe đạp", category: 'kanji', lesson: 5 },
  { id: 'l5-15', kanji: "歩いて", reading: "あるいて", meaning: "đi bộ", category: 'general', lesson: 5 },
  { id: 'l5-16', kanji: "人", reading: "ひと", meaning: "người", category: 'kanji', lesson: 5 },
  { id: 'l5-17', kanji: "友達", reading: "ともだち", meaning: "bạn, bạn bè", category: 'kanji', lesson: 5 },
  { id: 'l5-18', kanji: "彼", reading: "かれ", meaning: "anh ấy, bạn trai", category: 'kanji', lesson: 5 },
  { id: 'l5-19', kanji: "彼女", reading: "かのじょ", meaning: "chị ấy, bạn gái", category: 'kanji', lesson: 5 },
  { id: 'l5-20', kanji: "家族", reading: "かぞく", meaning: "gia đình", category: 'kanji', lesson: 5 },
  { id: 'l5-21', kanji: "一人で", reading: "ひとりで", meaning: "một mình", category: 'kanji', lesson: 5 },
  { id: 'l5-22', kanji: "先週", reading: "せんしゅう", meaning: "tuần trước", category: 'kanji', lesson: 5 },
  { id: 'l5-23', kanji: "今週", reading: "こんしゅう", meaning: "tuần này", category: 'kanji', lesson: 5 },
  { id: 'l5-24', kanji: "来週", reading: "らいしゅう", meaning: "tuần sau", category: 'kanji', lesson: 5 },
  { id: 'l5-25', kanji: "先月", reading: "せんげつ", meaning: "tháng trước", category: 'kanji', lesson: 5 },
  { id: 'l5-26', kanji: "今月", reading: "こんげつ", meaning: "tháng này", category: 'kanji', lesson: 5 },
  { id: 'l5-27', kanji: "来月", reading: "らいげつ", meaning: "tháng sau", category: 'kanji', lesson: 5 },
  { id: 'l5-28', kanji: "去年", reading: "きょねん", meaning: "năm ngoái", category: 'kanji', lesson: 5 },
  { id: 'l5-29', kanji: "ことし", reading: "ことし", meaning: "năm nay", category: 'general', lesson: 5 },
  { id: 'l5-30', kanji: "来年", reading: "らいねん", meaning: "sang năm", category: 'kanji', lesson: 5 },
  { id: 'l5-31', kanji: "1日", reading: "ついたち", meaning: "ngày mồng 1", category: 'kanji', lesson: 5 },
  { id: 'l5-32', kanji: "2日", reading: "ふつか", meaning: "ngày mồng 2, 2 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-33', kanji: "3日", reading: "みっか", meaning: "ngày mồng 3, 3 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-34', kanji: "4日", reading: "よっか", meaning: "ngày mồng 4, 4 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-35', kanji: "5日", reading: "いつか", meaning: "ngày mồng 5, 5 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-36', kanji: "6日", reading: "むいか", meaning: "ngày mồng 6, 6 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-37', kanji: "7日", reading: "なのか", meaning: "ngày mồng 7, 7 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-38', kanji: "8日", reading: "ようか", meaning: "ngày mồng 8, 8 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-39', kanji: "9日", reading: "ここのか", meaning: "ngày mồng 9, 9 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-40', kanji: "10日", reading: "とおか", meaning: "ngày mồng 10, 10 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-41', kanji: "14日", reading: "じゅうよっか", meaning: "ngày 14, 14 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-42', kanji: "20日", reading: "はつか", meaning: "ngày 20, 20 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-43', kanji: "24日", reading: "にじゅうよっか", meaning: "ngày 24, 24 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-44', kanji: "いつ", reading: "いつ", meaning: "bao giờ, khi nào", category: 'general', lesson: 5 },
  { id: 'l5-45', kanji: "誕生日", reading: "たんじょうび", meaning: "sinh nhật", category: 'kanji', lesson: 5 },

  // --- BÀI 6 ---
  { id: 'l6-1', kanji: "食べます", reading: "たべます", meaning: "ăn", category: 'verb', lesson: 6 },
  { id: 'l6-2', kanji: "飲みます", reading: "のみます", meaning: "uống", category: 'verb', lesson: 6 },
  { id: 'l6-3', kanji: "吸います", reading: "すいます", meaning: "hút [thuốc lá]", category: 'verb', lesson: 6 },
  { id: 'l6-4', kanji: "見ます", reading: "みます", meaning: "nhìn, xem", category: 'verb', lesson: 6 },
  { id: 'l6-5', kanji: "聞きます", reading: "ききます", meaning: "nghe", category: 'verb', lesson: 6 },
  { id: 'l6-6', kanji: "読みます", reading: "よみます", meaning: "đọc", category: 'verb', lesson: 6 },
  { id: 'l6-7', kanji: "書きます", reading: "かきます", meaning: "viết (vẽ)", category: 'verb', lesson: 6 },
  { id: 'l6-8', kanji: "買います", reading: "かいます", meaning: "mua", category: 'verb', lesson: 6 },
  { id: 'l6-9', kanji: "撮ります", reading: "とります", meaning: "chụp [ảnh]", category: 'verb', lesson: 6 },
  { id: 'l6-10', kanji: "します", reading: "します", meaning: "làm, chơi", category: 'verb', lesson: 6 },
  { id: 'l6-11', kanji: "会います", reading: "あいます", meaning: "gặp [bạn]", category: 'verb', lesson: 6 },
  { id: 'l6-12', kanji: "ごはん", reading: "ごはん", meaning: "bữa ăn, cơm", category: 'general', lesson: 6 },
  { id: 'l6-13', kanji: "朝ごはん", reading: "あさごはん", meaning: "cơm sáng, bữa sáng", category: 'kanji', lesson: 6 },
  { id: 'l6-14', kanji: "昼ごはん", reading: "ひるごはん", meaning: "cơm trưa, bữa trưa", category: 'kanji', lesson: 6 },
  { id: 'l6-15', kanji: "晩ごはん", reading: "ばんごはん", meaning: "cơm tối, bữa tối", category: 'kanji', lesson: 6 },
  { id: 'l6-16', kanji: "パン", reading: "パン", meaning: "bánh mì", category: 'general', lesson: 6 },
  { id: 'l6-17', kanji: "卵", reading: "たまご", meaning: "trứng", category: 'kanji', lesson: 6 },
  { id: 'l6-18', kanji: "肉", reading: "にく", meaning: "thịt", category: 'kanji', lesson: 6 },
  { id: 'l6-19', kanji: "魚", reading: "さかな", meaning: "cá", category: 'kanji', lesson: 6 },
  { id: 'l6-20', kanji: "野菜", reading: "やさい", meaning: "rau", category: 'kanji', lesson: 6 },
  { id: 'l6-21', kanji: "果物", reading: "くだもの", meaning: "hoa quả, trái cây", category: 'kanji', lesson: 6 },
  { id: 'l6-22', kanji: "水", reading: "みず", meaning: "nước", category: 'kanji', lesson: 6 },
  { id: 'l6-23', kanji: "お茶", reading: "おちゃ", meaning: "trà, trà xanh", category: 'kanji', lesson: 6 },
  { id: 'l6-24', kanji: "紅茶", reading: "こうちゃ", meaning: "trà đen", category: 'kanji', lesson: 6 },
  { id: 'l6-25', kanji: "牛乳", reading: "ぎゅうにゅう", meaning: "sữa bò", category: 'kanji', lesson: 6 },
  { id: 'l6-26', kanji: "ジュース", reading: "ジュース", meaning: "nước hoa quả", category: 'general', lesson: 6 },
  { id: 'l6-27', kanji: "ビール", reading: "ビール", meaning: "bia", category: 'general', lesson: 6 },
  { id: 'l6-28', kanji: "[お]酒", reading: "[お]さけ", meaning: "rượu, rượu gạo Nhật", category: 'kanji', lesson: 6 },
  { id: 'l6-29', kanji: "たばこ", reading: "たばこ", meaning: "thuốc lá", category: 'general', lesson: 6 },
  { id: 'l6-30', kanji: "手紙", reading: "てがみ", meaning: "thư", category: 'kanji', lesson: 6 },
  { id: 'l6-31', kanji: "レポート", reading: "レポート", meaning: "báo cáo", category: 'general', lesson: 6 },
  { id: 'l6-32', kanji: "写真", reading: "しゃしん", meaning: "ảnh", category: 'kanji', lesson: 6 },
  { id: 'l6-33', kanji: "ビデオ", reading: "ビデオ", meaning: "băng video, đầu video", category: 'general', lesson: 6 },
  { id: 'l6-34', kanji: "店", reading: "みせ", meaning: "cửa hàng, tiệm", category: 'kanji', lesson: 6 },
  { id: 'l6-35', kanji: "庭", reading: "にわ", meaning: "vườn", category: 'kanji', lesson: 6 },
  { id: 'l6-36', kanji: "宿題", reading: "しゅくだい", meaning: "bài tập về nhà", category: 'kanji', lesson: 6 },
  { id: 'l6-37', kanji: "テニス", reading: "テニス", meaning: "quần vợt", category: 'general', lesson: 6 },
  { id: 'l6-38', kanji: "サッカー", reading: "サッカー", meaning: "bóng đá", category: 'general', lesson: 6 },
  { id: 'l6-39', kanji: "[お]花見", reading: "[お]はなみ", meaning: "(việc) ngắm hoa anh đào", category: 'kanji', lesson: 6 },
  { id: 'l6-40', kanji: "何", reading: "なに", meaning: "cái gì, gì", category: 'kanji', lesson: 6 },
  { id: 'l6-41', kanji: "いっしょに", reading: "いっしょに", meaning: "cùng, cùng nhau", category: 'general', lesson: 6 },
  { id: 'l6-42', kanji: "ちょっと", reading: "ちょっと", meaning: "một chút", category: 'general', lesson: 6 },
  { id: 'l6-43', kanji: "いつも", reading: "いつも", meaning: "luôn luôn, lúc nào cũng", category: 'general', lesson: 6 },
  { id: 'l6-44', kanji: "時々", reading: "ときどき", meaning: "thỉnh thoảng", category: 'kanji', lesson: 6 },
  { id: 'l6-45', kanji: "それから", reading: "それから", meaning: "sau đó, tiếp theo", category: 'general', lesson: 6 },

  // --- BÀI 7 ---
  { id: 'l7-1', kanji: "切ります", reading: "きります", meaning: "cắt", category: 'verb', lesson: 7 },
  { id: 'l7-2', kanji: "送ります", reading: "おくります", meaning: "gửi", category: 'verb', lesson: 7 },
  { id: 'l7-3', kanji: "あげます", reading: "あげます", meaning: "cho, tặng", category: 'verb', lesson: 7 },
  { id: 'l7-4', kanji: "もらいます", reading: "もらいます", meaning: "nhận", category: 'verb', lesson: 7 },
  { id: 'l7-5', kanji: "貸します", reading: "かします", meaning: "cho mượn, cho vay", category: 'verb', lesson: 7 },
  { id: 'l7-6', kanji: "借ります", reading: "かります", meaning: "mượn, vay", category: 'verb', lesson: 7 },
  { id: 'l7-7', kanji: "教えます", reading: "おしえます", meaning: "dạy", category: 'verb', lesson: 7 },
  { id: 'l7-8', kanji: "習います", reading: "ならいます", meaning: "học, tập", category: 'verb', lesson: 7 },
  { id: 'l7-9', kanji: "電話をかけます", reading: "でんわをかけます", meaning: "gọi [điện thoại]", category: 'verb', lesson: 7 },
  { id: 'l7-10', kanji: "手", reading: "て", meaning: "tay", category: 'kanji', lesson: 7 },
  { id: 'l7-11', kanji: "はし", reading: "はし", meaning: "đũa", category: 'general', lesson: 7 },
  { id: 'l7-12', kanji: "スプーン", reading: "スプーン", meaning: "thìa", category: 'general', lesson: 7 },
  { id: 'l7-13', kanji: "ナイフ", reading: "ナイフ", meaning: "dao", category: 'general', lesson: 7 },
  { id: 'l7-14', kanji: "フォーク", reading: "フォーク", meaning: "đĩa, nĩa", category: 'general', lesson: 7 },
  { id: 'l7-15', kanji: "はさみ", reading: "はさみ", meaning: "kéo", category: 'general', lesson: 7 },
  { id: 'l7-16', kanji: "パソコン", reading: "パソコン", meaning: "máy vi tính cá nhân", category: 'general', lesson: 7 },
  { id: 'l7-17', kanji: "ケータイ", reading: "ケータイ", meaning: "điện thoại di động", category: 'general', lesson: 7 },
  { id: 'l7-18', kanji: "パンチ", reading: "パンチ", meaning: "cái đục lỗ", category: 'general', lesson: 7 },
  { id: 'l7-19', kanji: "ホッチキス", reading: "ホッチキス", meaning: "cái dập ghim", category: 'general', lesson: 7 },
  { id: 'l7-20', kanji: "セロテープ", reading: "セロテープ", meaning: "băng dính", category: 'general', lesson: 7 },
  { id: 'l7-21', kanji: "消しゴム", reading: "けしゴム", meaning: "cái tẩy, cục tẩy", category: 'kanji', lesson: 7 },
  { id: 'l7-22', kanji: "紙", reading: "かみ", meaning: "giấy", category: 'kanji', lesson: 7 },
  { id: 'l7-23', kanji: "メール", reading: "メール", meaning: "thư điện tử, email", category: 'general', lesson: 7 },
  { id: 'l7-24', kanji: "年賀状", reading: "ねんがじょう", meaning: "thiệp mừng năm mới", category: 'kanji', lesson: 7 },
  { id: 'l7-25', kanji: "花", reading: "はな", meaning: "hoa", category: 'kanji', lesson: 7 },
  { id: 'l7-26', kanji: "シャツ", reading: "シャツ", meaning: "áo sơ mi", category: 'general', lesson: 7 },
  { id: 'l7-27', kanji: "プレゼント", reading: "プレゼント", meaning: "quà tặng, tặng phẩm", category: 'general', lesson: 7 },
  { id: 'l7-28', kanji: "荷物", reading: "にもつ", meaning: "đồ đạc, hành lý", category: 'kanji', lesson: 7 },
  { id: 'l7-29', kanji: "お金", reading: "おかね", meaning: "tiền", category: 'kanji', lesson: 7 },
  { id: 'l7-30', kanji: "切符", reading: "きっぷ", meaning: "vé", category: 'kanji', lesson: 7 },
  { id: 'l7-31', kanji: "クリスマス", reading: "クリスマス", meaning: "Giáng sinh", category: 'general', lesson: 7 },
  { id: 'l7-32', kanji: "父", reading: "ちち", meaning: "bố (của mình)", category: 'kanji', lesson: 7 },
  { id: 'l7-33', kanji: "母", reading: "はは", meaning: "mẹ (của mình)", category: 'kanji', lesson: 7 },
  { id: 'l7-34', kanji: "お父さん", reading: "おとうさん", meaning: "bố (của người khác)", category: 'kanji', lesson: 7 },
  { id: 'l7-35', kanji: "お母さん", reading: "おかあさん", meaning: "mẹ (của người khác)", category: 'kanji', lesson: 7 },
  { id: 'l7-36', kanji: "もう", reading: "もう", meaning: "đã, rồi", category: 'general', lesson: 7 },
  { id: 'l7-37', kanji: "まだ", reading: "まだ", meaning: "chưa", category: 'general', lesson: 7 },
  { id: 'l7-38', kanji: "これから", reading: "これから", meaning: "từ bây giờ, sau đây", category: 'general', lesson: 7 },
  { id: 'l7-c1', kanji: "すてきですね", reading: "すてきですね", meaning: "hay nhỉ / đẹp nhỉ", category: 'general', lesson: 7 },
  { id: 'l7-c2', kanji: "いらっしゃい", reading: "いらっしゃい", meaning: "Rất hoan nghênh anh/chị đến chơi.", category: 'general', lesson: 7 },
  { id: 'l7-c3', kanji: "どうぞ お上がりください", reading: "どうぞ おあがりください", meaning: "Mời anh/chị vào.", category: 'kanji', lesson: 7 },
  { id: 'l7-c4', kanji: "失礼します", reading: "しつれいします", meaning: "Xin phép tôi vào. (khi bước vào nhà)", category: 'kanji', lesson: 7 },
  { id: 'l7-c5', kanji: "[～は] いかがですか", reading: "[～は] いかがですか", meaning: "Anh/Chị dùng [~] nhé?", category: 'general', lesson: 7 },
  { id: 'l7-c6', kanji: "いただきます", reading: "いただきます", meaning: "Mời anh/chị dùng ~. (trước khi ăn)", category: 'general', lesson: 7 },
  { id: 'l7-c7', kanji: "ごちそうさまでした", reading: "ごちそうさまでした", meaning: "Xin cám ơn đã đãi tôi bữa ăn ngon.", category: 'general', lesson: 7 },
  { id: 'l7-q1', kanji: "スペイン", reading: "スペイン", meaning: "Tây Ban Nha", category: 'general', lesson: 7 },

  // --- BÀI 8 ---
  { id: 'l8-1', kanji: "ハンサム [な]", reading: "ハンサム", meaning: "đẹp trai", category: 'general', lesson: 8 },
  { id: 'l8-2', kanji: "きれい [な]", reading: "きれい", meaning: "đẹp, sạch", category: 'general', lesson: 8 },
  { id: 'l8-3', kanji: "静か [な]", reading: "しずか", meaning: "yên tĩnh", category: 'kanji', lesson: 8 },
  { id: 'l8-4', kanji: "にぎやか [な]", reading: "にぎやか", meaning: "náo nhiệt", category: 'general', lesson: 8 },
  { id: 'l8-5', kanji: "有名 [な]", reading: "ゆうめい", meaning: "nổi tiếng", category: 'kanji', lesson: 8 },
  { id: 'l8-6', kanji: "親切 [な]", reading: "しんせつ", meaning: "tốt bụng, thân thiện", category: 'kanji', lesson: 8 },
  { id: 'l8-7', kanji: "元気 [な]", reading: "げんき", meaning: "khỏe, khỏe khoắn", category: 'kanji', lesson: 8 },
  { id: 'l8-8', kanji: "暇 [な]", reading: "ひま", meaning: "rảnh rỗi", category: 'kanji', lesson: 8 },
  { id: 'l8-9', kanji: "便利 [な]", reading: "べんり", meaning: "tiện lợi", category: 'kanji', lesson: 8 },
  { id: 'l8-10', kanji: "すてき [な]", reading: "すてき", meaning: "đẹp, hay, tuyệt vời", category: 'general', lesson: 8 },
  { id: 'l8-11', kanji: "大きい", reading: "おおきい", meaning: "to, lớn", category: 'kanji', lesson: 8 },
  { id: 'l8-12', kanji: "小さい", reading: "ちいさい", meaning: "nhỏ, bé", category: 'kanji', lesson: 8 },
  { id: 'l8-13', kanji: "新しい", reading: "あたらしい", meaning: " mới", category: 'kanji', lesson: 8 },
  { id: 'l8-14', kanji: "古い", reading: "ふるい", meaning: "cũ", category: 'kanji', lesson: 8 },
  { id: 'l8-15', kanji: "いい（よい）", reading: "いい", meaning: "tốt", category: 'general', lesson: 8 },
  { id: 'l8-16', kanji: "悪い", reading: "わるい", meaning: "xấu", category: 'kanji', lesson: 8 },
  { id: 'l8-17', kanji: "暑い", reading: "あつい", meaning: "nóng (thời tiết)", category: 'kanji', lesson: 8 },
  { id: 'l8-18', kanji: "熱い", reading: "あつい", meaning: "nóng (cảm giác)", category: 'kanji', lesson: 8 },
  { id: 'l8-19', kanji: "寒い", reading: "さむい", meaning: "lạnh (thời tiết)", category: 'kanji', lesson: 8 },
  { id: 'l8-20', kanji: "冷たい", reading: "つめたい", meaning: "lạnh (cảm giác)", category: 'kanji', lesson: 8 },
  { id: 'l8-21', kanji: "難しい", reading: "むずかしい", meaning: "khó", category: 'kanji', lesson: 8 },
  { id: 'l8-22', kanji: "易しい", reading: "やさしい", meaning: "dễ", category: 'kanji', lesson: 8 },
  { id: 'l8-23', kanji: "高い", reading: "たかい", meaning: "đắt, cao", category: 'kanji', lesson: 8 },
  { id: 'l8-24', kanji: "安い", reading: "やすい", meaning: "rẻ", category: 'kanji', lesson: 8 },
  { id: 'l8-25', kanji: "低い", reading: "ひくい", meaning: "thấp", category: 'kanji', lesson: 8 },
  { id: 'l8-26', kanji: "おもしろい", reading: "おもしろい", meaning: "thú vị, hay", category: 'general', lesson: 8 },
  { id: 'l8-27', kanji: "おいしい", reading: "おいしい", meaning: "ngon", category: 'general', lesson: 8 },
  { id: 'l8-28', kanji: "忙しい", reading: "いそがしい", meaning: "bận", category: 'kanji', lesson: 8 },
  { id: 'l8-29', kanji: "楽しい", reading: "たのしい", meaning: "vui", category: 'kanji', lesson: 8 },
  { id: 'l8-30', kanji: "白い", reading: "しろい", meaning: "trắng", category: 'kanji', lesson: 8 },
  { id: 'l8-31', kanji: "黒い", reading: "くろい", meaning: "đen", category: 'kanji', lesson: 8 },
  { id: 'l8-32', kanji: "赤い", reading: "あかい", meaning: "đỏ", category: 'kanji', lesson: 8 },
  { id: 'l8-33', kanji: "青い", reading: "あおい", meaning: "xanh da trời", category: 'kanji', lesson: 8 },
  { id: 'l8-34', kanji: "桜", reading: "さくら", meaning: "anh đào (hoa, cây)", category: 'kanji', lesson: 8 },
  { id: 'l8-35', kanji: "山", reading: "やま", meaning: "núi", category: 'kanji', lesson: 8 },
  { id: 'l8-36', kanji: "町", reading: "まち", meaning: "thị trấn, thị xã, thành phố", category: 'kanji', lesson: 8 },
  { id: 'l8-37', kanji: "食べ物", reading: "たべもの", meaning: "đồ ăn", category: 'kanji', lesson: 8 },
  { id: 'l8-38', kanji: "所", reading: "ところ", meaning: "nơi, chỗ", category: 'kanji', lesson: 8 },
  { id: 'l8-39', kanji: "寮", reading: "りょう", meaning: "kí túc xá", category: 'kanji', lesson: 8 },
  { id: 'l8-40', kanji: "レストラン", reading: "レストラン", meaning: "nhà hàng", category: 'general', lesson: 8 },
  { id: 'l8-41', kanji: "生活", reading: "せいかつ", meaning: "cuộc sống, sinh hoạt", category: 'kanji', lesson: 8 },
  { id: 'l8-42', kanji: "[お] 仕事", reading: "[お]しごと", meaning: "công việc", category: 'kanji', lesson: 8 },
  { id: 'l8-43', kanji: "どう", reading: "どう", meaning: "thế nào", category: 'general', lesson: 8 },
  { id: 'l8-44', kanji: "どんな ～", reading: "どんな", meaning: "~ như thế nào", category: 'general', lesson: 8 },
  { id: 'l8-45', kanji: "とても", reading: "とても", meaning: "rất, lắm", category: 'general', lesson: 8 },
  { id: 'l8-46', kanji: "あまり", reading: "あまり", meaning: "không ~ lắm (phủ định)", category: 'general', lesson: 8 },
  { id: 'l8-47', kanji: "そして", reading: "そして", meaning: "và, thêm nữa", category: 'general', lesson: 8 },
  { id: 'l8-48', kanji: "～が、～", reading: "～が", meaning: "~, nhưng ~", category: 'general', lesson: 8 },
  { id: 'l8-c1', kanji: "お元気ですか", reading: "おげんきですか", meaning: "Anh/Chị có khỏe không?", category: 'kanji', lesson: 8 },
  { id: 'l8-c2', kanji: "そうですね", reading: "そうですね", meaning: "Thế à / Để tôi xem", category: 'general', lesson: 8 },
  { id: 'l8-c3', kanji: "もう いっぱい いかがですか", reading: "もう いっぱい いかがですか", meaning: "Anh/Chị dùng thêm một chén nữa nhé?", category: 'general', lesson: 8 },
  { id: 'l8-c4', kanji: "けっこうです", reading: "けっこうです", meaning: "Không, đủ rồi ạ", category: 'general', lesson: 8 },
  { id: 'l8-c5', kanji: "もう ～ですね", reading: "もう ～ですね", meaning: "Đã ~ rồi nhỉ", category: 'general', lesson: 8 },
  { id: 'l8-c6', kanji: "そろそろ しつれいします", reading: "そろそろ しつれいします", meaning: "Sắp đến lúc tôi phải xin phép rồi", category: 'general', lesson: 8 },
  { id: 'l8-c7', kanji: "また いらっしゃってください", reading: "また いらっしゃってください", meaning: "Lần sau anh/chị lại đến chơi nhé", category: 'general', lesson: 8 },
  { id: 'l8-q1', kanji: "シャンハイ", reading: "シャンハイ", meaning: "Thượng Hải", category: 'general', lesson: 8 },
  { id: 'l8-q2', kanji: "金閣寺", reading: "きんかくじ", meaning: "Chùa Kinkaku-ji (Chùa Vàng)", category: 'kanji', lesson: 8 },
  { id: 'l8-q3', kanji: "奈良公園", reading: "ならこうえん", meaning: "Công viên Nara", category: 'kanji', lesson: 8 },
  { id: 'l8-q4', kanji: "富士山", reading: "ふじさん", meaning: "Núi Phú Sĩ", category: 'kanji', lesson: 8 },
  { id: 'l8-q5', kanji: "「七人の侍」", reading: "「しちにんのさむらい」", meaning: "7 chàng võ sĩ Samurai (phim)", category: 'kanji', lesson: 8 },

  // --- BÀI 9 ---
  { id: 'l9-1', kanji: "わかります", reading: "わかります", meaning: "hiểu, nắm được", category: 'verb', lesson: 9 },
  { id: 'l9-2', kanji: "あります", reading: "あります", meaning: "có (sở hữu)", category: 'verb', lesson: 9 },
  { id: 'l9-3', kanji: "好き [な]", reading: "すき", meaning: "thích", category: 'general', lesson: 9 },
  { id: 'l9-4', kanji: "嫌い [な]", reading: "きらい", meaning: "ghét, không thích", category: 'general', lesson: 9 },
  { id: 'l9-5', kanji: "上手 [な]", reading: "じょうず", meaning: "giỏi, khéo", category: 'general', lesson: 9 },
  { id: 'l9-6', kanji: "下手 [な]", reading: "へた", meaning: "kém", category: 'general', lesson: 9 },
  { id: 'l9-7', kanji: "飲み物", reading: "のみもの", meaning: "đồ uống", category: 'kanji', lesson: 9 },
  { id: 'l9-8', kanji: "料理", reading: "りょうり", meaning: "món ăn, việc nấu ăn", category: 'kanji', lesson: 9 },
  { id: 'l9-9', kanji: "スポーツ", reading: "スポーツ", meaning: "thể thao", category: 'general', lesson: 9 },
  { id: 'l9-10', kanji: "野球", reading: "やきゅう", meaning: "bóng chày", category: 'kanji', lesson: 9 },
  { id: 'l9-11', kanji: "ダンス", reading: "ダンス", meaning: "nhảy, khiêu vũ", category: 'general', lesson: 9 },
  { id: 'l9-12', kanji: "旅行", reading: "りょこう", meaning: "du lịch, chuyến du lịch", category: 'kanji', lesson: 9 },
  { id: 'l9-13', kanji: "音楽", reading: "おんがく", meaning: "âm nhạc", category: 'kanji', lesson: 9 },
  { id: 'l9-14', kanji: "歌", reading: "うた", meaning: "bài hát", category: 'kanji', lesson: 9 },
  { id: 'l9-15', kanji: "クラシック", reading: "クラシック", meaning: "nhạc cổ điển", category: 'general', lesson: 9 },
  { id: 'l9-16', kanji: "ジャズ", reading: "ジャズ", meaning: "nhạc jazz", category: 'general', lesson: 9 },
  { id: 'l9-17', kanji: "コンサート", reading: "コンサート", meaning: "buổi hòa nhạc", category: 'general', lesson: 9 },
  { id: 'l9-18', kanji: "カラオケ", reading: "カラオケ", meaning: "karaoke", category: 'general', lesson: 9 },
  { id: 'l9-19', kanji: "歌舞伎", reading: "かぶき", meaning: "Kabuki (kịch truyền thống Nhật)", category: 'kanji', lesson: 9 },
  { id: 'l9-20', kanji: "絵", reading: "え", meaning: "tranh, hội họa", category: 'kanji', lesson: 9 },
  { id: 'l9-21', kanji: "字", reading: "じ", meaning: "chữ", category: 'kanji', lesson: 9 },
  { id: 'l9-22', kanji: "漢字", reading: "かんじ", meaning: "chữ Hán", category: 'kanji', lesson: 9 },
  { id: 'l9-23', kanji: "ひらがな", reading: "ひらがな", meaning: "chữ Hiragana", category: 'general', lesson: 9 },
  { id: 'l9-24', kanji: "かたかな", reading: "かたかな", meaning: "chữ Katakana", category: 'general', lesson: 9 },
  { id: 'l9-25', kanji: "ローマ字", reading: "ローマじ", meaning: "chữ La Mã", category: 'kanji', lesson: 9 },
  { id: 'l9-26', kanji: "細かい お金", reading: "こまかい おかね", meaning: "tiền lẻ", category: 'kanji', lesson: 9 },
  { id: 'l9-27', kanji: "チケット", reading: "チケット", meaning: "vé", category: 'general', lesson: 9 },
  { id: 'l9-28', kanji: "時間", reading: "じかん", meaning: "thời gian", category: 'kanji', lesson: 9 },
  { id: 'l9-29', kanji: "用事", reading: "ようじ", meaning: "việc bận, công chuyện", category: 'kanji', lesson: 9 },
  { id: 'l9-30', kanji: "約束", reading: "やくそく", meaning: "cuộc hẹn, lời hứa", category: 'kanji', lesson: 9 },
  { id: 'l9-31', kanji: "アルバイト", reading: "アルバイト", meaning: "việc làm thêm", category: 'general', lesson: 9 },
  { id: 'l9-32', kanji: "ご主人", reading: "ごしゅじん", meaning: "chồng (của người khác)", category: 'kanji', lesson: 9 },
  { id: 'l9-33', kanji: "夫 / 主人", reading: "おっと / しゅじん", meaning: "chồng (của mình)", category: 'kanji', lesson: 9 },
  { id: 'l9-34', kanji: "奥さん", reading: "おくさん", meaning: "vợ (của người khác)", category: 'kanji', lesson: 9 },
  { id: 'l9-35', kanji: "妻 / 家内", reading: "つま / かない", meaning: "vợ (của mình)", category: 'kanji', lesson: 9 },
  { id: 'l9-36', kanji: "子ども", reading: "こども", meaning: "con cái", category: 'kanji', lesson: 9 },
  { id: 'l9-37', kanji: "よく", reading: "よく", meaning: "tốt, rõ (chỉ mức độ)", category: 'general', lesson: 9 },
  { id: 'l9-38', kanji: "だいたい", reading: "だいたい", meaning: "đại khái, đại thể", category: 'general', lesson: 9 },
  { id: 'l9-39', kanji: "たくさん", reading: "たくさん", meaning: "nhiều", category: 'general', lesson: 9 },
  { id: 'l9-40', kanji: "少し", reading: "すこし", meaning: "ít, một ít", category: 'kanji', lesson: 9 },
  { id: 'l9-41', kanji: "全然", reading: "ぜんぜん", meaning: "hoàn toàn ~ không (phủ định)", category: 'kanji', lesson: 9 },
  { id: 'l9-42', kanji: "早く / 速く", reading: "はやく", meaning: "sớm, nhanh", category: 'kanji', lesson: 9 },
  { id: 'l9-43', kanji: "～から", reading: "から", meaning: "vì ~", category: 'general', lesson: 9 },
  { id: 'l9-44', kanji: "どうして", reading: "どうして", meaning: "tại sao", category: 'general', lesson: 9 },
  { id: 'l9-c1', kanji: "貸してください", reading: "かしてください", meaning: "Hãy cho tôi mượn (nó).", category: 'kanji', lesson: 9 },
  { id: 'l9-c2', kanji: "いいですよ", reading: "いいですよ", meaning: "Được chứ. Được ạ.", category: 'general', lesson: 9 },
  { id: 'l9-c3', kanji: "残念です [が]", reading: "ざんねんです", meaning: "Đáng tiếc là... / Tôi xin lỗi, [nhưng...]", category: 'general', lesson: 9 },
  { id: 'l9-c4', kanji: "ああ", reading: "ああ", meaning: "A / Ôi", category: 'general', lesson: 9 },
  { id: 'l9-c5', kanji: "いっしょに いかがですか", reading: "いっしょに いかがですか", meaning: "Anh/Chị cùng ~ với tôi không?", category: 'general', lesson: 9 },
  { id: 'l9-c6', kanji: "[～は] ちょっと･･････", reading: "ちょっと", meaning: "[~ thì] có lẽ không được rồi. (từ chối khéo)", category: 'general', lesson: 9 },
  { id: 'l9-c7', kanji: "だめですか", reading: "だめですか", meaning: "Không được à?", category: 'general', lesson: 9 },
  { id: 'l9-c8', kanji: "また 今度 お願いします", reading: "また こんど おねがいします", meaning: "Hẹn anh/chị lần sau vậy.", category: 'kanji', lesson: 9 },

  // --- CÁC BÀI TIẾP THEO (PLACEHOLDERS) ---
  { id: 'l10-1', kanji: "ある", reading: "あります", meaning: "Có (đồ vật)", category: 'verb', lesson: 10 },
  { id: 'l11-1', kanji: "一つ", reading: "ひとつ", meaning: "1 cái (đếm vật)", category: 'kanji', lesson: 11 },
  { id: 'l12-1', kanji: "簡単", reading: "かんたん", meaning: "Đơn giản", category: 'general', lesson: 12 },
  { id: 'l13-1', kanji: "遊ぶ", reading: "あそびます", meaning: "Chơi", category: 'verb', lesson: 13 },
  { id: 'l14-1', kanji: "点ける", reading: "つけます", meaning: "Bật (đèn)", category: 'verb', lesson: 14 },
  { id: 'l15-1', kanji: "置く", reading: "おきます", meaning: "Đặt, để", category: 'verb', lesson: 15 },
  { id: 'l16-1', kanji: "乗る", reading: "のります", meaning: "Lên (tàu/xe)", category: 'verb', lesson: 16 },
  { id: 'l17-1', kanji: "覚える", reading: "おぼえます", meaning: "Ghi nhớ", category: 'verb', lesson: 17 },
  { id: 'l18-1', kanji: "できる", reading: "できます", meaning: "Có thể", category: 'verb', lesson: 18 },
  { id: 'l19-1', kanji: "登る", reading: "のぼります", meaning: "Leo (núi)", category: 'verb', lesson: 19 },
  { id: 'l20-1', kanji: "要る", reading: "いります", meaning: "Cần", category: 'verb', lesson: 20 },
  { id: 'l21-1', kanji: "思う", reading: "おもいます", meaning: "Nghĩ là", category: 'verb', lesson: 21 },
  { id: 'l22-1', kanji: "着る", reading: "きます", meaning: "Mặc (áo)", category: 'verb', lesson: 22 },
  { id: 'l23-1', kanji: "聞く", reading: "ききます", meaning: "Hỏi (thầy cô)", category: 'verb', lesson: 23 },
  { id: 'l24-1', kanji: "くれる", reading: "くれます", meaning: "Cho, tặng (tôi)", category: 'verb', lesson: 24 },
  { id: 'l25-1', kanji: "考える", reading: "かんがえます", meaning: "Suy nghĩ", category: 'verb', lesson: 25 }
];

export const SYSTEM_PROMPT = `Bạn là một giáo viên tiếng Nhật chuyên gia, hỗ trợ học sinh luyện thi JLPT N5 dựa trên giáo trình Minna no Nihongo. 
Khi giải thích một từ vựng:
1. Giải thích ý nghĩa rõ ràng theo đúng ngữ cảnh sơ cấp.
2. Cung cấp ví dụ thực tế đơn giản phù hợp trình độ N5.
3. Giải thích cách dùng trong ngữ cảnh văn hóa Nhật Bản.
4. Trả lời bằng tiếng Việt thân thiện.
5. Nếu là động từ, hãy nhắc đến nhóm động từ (1, 2, 3).`;
